### ISSUE TITLE
Create Service to return used Safe Apps

### ISSUE THREAD

**Issue by Graeme-Code** [gnosis/safe-config-service#193]
**Requires Estimation**

**Background** 

According to roadmap issue: https://github.com/gnosis/safe/issues/451

It's a problem for repeat users to find Safe Apps which have been used before. 

**Solution: **
Create a sub-menu in Safe Apps which displays Safe Apps that a user has made a transaction with. For the frontend to do this, we need a service which will return the Safe Apps that the Safe has made a transaction with. 

**Definition of done**

An API endpoint which accepts a smart contract address and returns a JSON. JSON should be an ordered list of Safe Apps, ordered from most transacted with to least. 

**edge cases**
When Safe Apps have the same number of transactions,  the Safe Apps should be returned according to alphabetical order of the Safe Apps name. 

Approve transaction done via a Safe App should not included in the count of transactions.

**Comment by fmrsabino** [comment]
According to gnosis/safe#451 there are two proposed solutions from the client perspective:

- Implement manual Safe apps favorites
- Have a special list or section for the most recent or most used Safe apps.

I will do my best to give a technical perspective on this proposal and also some additional suggestions:

#  Solution 1: Implement manual Safe apps favorites

This is the easiest solution of the two, no matter if a service is used or not. It's also a solution that would require some manual input and management by our users.

## Solution 1a. Frontend only

This can be solved on the Frontend side by storing locally the favourite apps for each user.

Advantages:
\+  No service required
\+ implementation effort low

Disadvantages:
\- Having it stored locally means that it does now work cross environments (different browsers, hosts, etc...)

## Solution 1b. Frontend + Config Service

If we decide to store this information on the config service, it's going to increase its scope. I think from all the services that we provide, the config-service is indeed the correct place to store this kind of information since it's more app related metadata that we show and use.

Advantages:
\+ The configuration is synced between multiple clients
\+ Implementation effort low. For a given safe address, we store a list of favourite apps

#  Solution 2: Have a special list or section for the most recent or most used Safe apps.

Here we have two components.

- Most recent 
- Most used

Here we can either rely on transaction data (more effort but we get more "validated" data) or just clicks/loading dapps (less effort but does not track real interactions with a dApp and we might have privacy concerns on registering this).

A solution which is based on just the Frontend would not be ideal since these metrics would be lost if tracked locally which reduces the value provided by this feature.

So the solutions where I see that this can be solved from our service perspective do require more effort than anything proposed on `Solution 1`

## Solution 2a. Frontend + Config Service

Adding Safe App usage per safe on the config service would mean the feature is contextualised – the config service already handles listing of SafeApps so given our current infrastructure, it'd be the place to also handle these kinds of requests.

Advantages:
\+ The configuration is synced between multiple clients
\+ It is based on real, blockchain data

Disadvantages:
\- Adding node/rpc logic to the config service + decoding transactions
\- Complexity and scope of the service increase a lot

## Solution 2b. Frontend + Config Service + Core Services (?)

Maybe we can rely already on the node configuration of core services and decoding capabilities in order to help with the feature implementation. I have a lot of open questions regarding this – the core services are already a central part of our infrastructure and adding this feature might also be something that we do not want there (to separate this transaction execution infrastructure from safe-app support).

Advantages:
\+ The configuration is synced between multiple clients
\+ It is based on real, blockchain data
\+ The config service remains a node-less service (requiring less maintenance)

Disadvantages:
\- The config service might now depend on the core services
\- Core service implementation

## Solution 2c. Frontend + External Provider (?)

More like an open question. Do we know an external provider that can already provide this blockchain data in an easy way?

**Comment by rmeissner** [comment]
Solution 1a was chosen, therefore no backend is requried
