### ISSUE TITLE
Include `L1` or `L2` information for chains

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-config-service#203]
## Feature

The web app needs to know to which layer any given chain corresponds to.

### Proposal 1
Add the field `layer` to the current `ChainInfo` payload.

```json
{
  "chainId":"4",
  "chainName":"Rinkeby",
  // ...
  "layer":"1" // <stringified-int> 
}
```

Currently `layer` could only take values of either `"1"` or `"2"`

### Proposal 2

(I am not sure I understood the comment correctly)
Return a map of the address to contract for the safe related contracts as part of the chain info. (see https://github.com/gnosis/safe-deployments)

**Comment by rmeissner** [comment]
Could we add information why this information is required (e.g. what decision are based on this) ?

**Comment by dasanra** [comment]
In this case in web we opted by this solution because we were already using safe-deployments so a flag to detect whether we should use L1 or L2 function to fetch the safe instance was enough.

If we don't expect to use other different smart contract instances depending on the chain layer (multisend, fallbackhandler...) we could just return the correct gnosisSafe instance address. But if some other smart contracts could also be different depending on network we will need addresses for all the others in future

**Comment by fmrsabino** [comment]
This information is more or less available via the `/api/v1/about/master-copies/` endpoint of the core services. We can think about piping it though the client gateway instead 🤔 

How would you fetch this information @dasanra ? On per chain basis or do you need it to be present on a collection view of the chains (array with all the chains and corresponding data)?

**Comment by rmeissner** [comment]
We should change the purpose of the issue to return the information missing to completely remove network specific configurations from the safe-react project. A big part of this would be the contract addresses (e.g. default mastercopy, proxy factory, etc).

**Comment by fmrsabino** [comment]
@gnosis/safe-web can you share what information is required for this?

**Comment by katspaugh** [comment]
We currently use the safe-deployments repo for contract addresses. The problem is, [safe-deployments exports two functions](https://github.com/gnosis/safe-deployments/blob/main/src/safes.ts#L14-L23):

* getSafeSingletonDeployment
* getSafeL2SingletonDeployment

And we don't know which one to call for which network. I mean, we know that Polygon is L2, but the app doesn't.

**Comment by katspaugh** [comment]
These are just the two functions that differ depending on L1/L2. We also use:
* getProxyFactoryDeployment
* getFallbackHandlerDeployment
* getMultiSendCallOnlyDeployment

So if we go the route of adding the deployment artifacts to the config service, those 3 should also be there.

**Comment by fmrsabino** [comment]
Got it. But how do you use those functions? Which fields do you require to be returned by the config-service so that the migration on your side is done without issues?

I think it'd be better to start with a json payload proposal from the client side.

**Comment by mikheevm** [comment]
> And we don't know which one to call for which network. I mean, we know that Polygon is L2, but the app doesn't.

There's only one L1 network - the mainnet. So cannot it be hardcoded for the network with chain id 1?

**Comment by katspaugh** [comment]
I think rinkeby is also L1.

**Comment by katspaugh** [comment]
@fmrsabino the proposal in this issue description will definitely satisfy our need in the short term. We can continue using the safe-deployments repo in combination with that.

**Comment by rmeissner** [comment]
As mentioned in our meeting, if we pull the information from the service about what networks are supported then we should switch away from the safe-deployments. There are currently a couple of addresses that I see depend on the network (and in the near future L1 or L2 is not enough to differentiate this):
- proxy factory
- mastercopy/ singleton address
- fallback handler
- multisend/ multisendcallonly
- allowance module

There fore I would propose that the backend returns an object `contracts` where the keys are the contracts mentioned above. For example:
```json
{
  "chainId": "1",
  "chainName": "Mainnet",
  "contracts": {
    "factory": "<factory_address>",
    "singleton": "<singleton_address>",
    "fallback": "<fallback_handler_address>",
    "multisend": "<multisend_address>",
    "allowances": "<allowance_module_address>"
  }
}
```

**Comment by katspaugh** [comment]
I like the suggestion above, that would allow us to remove the safe-deployments dependency.
I guess the maintenance effort on the admin side would be the same as updating the safe-deployments repo.

Since 1.3.0 contracts support earlier safes (1.1.1), we probably wouldn't need to maintain any legacy contract addresses on config service?

**Comment by fmrsabino** [comment]
> I like the suggestion above, that would allow us to remove the safe-deployments dependency.
> I guess the maintenance effort on the admin side would be the same as updating the safe-deployments repo.
> 
> Since 1.3.0 contracts support earlier safes (1.1.1), we probably wouldn't need to maintain any legacy contract addresses on config service?

Would the payload that @rmeissner suggested work for what you need on the client side?

**Comment by katspaugh** [comment]
Yes, unless we want to keep supporting 1.1.1.
As of now, we have this in the code:
<img width="934" alt="Screenshot 2021-09-07 at 11 49 02" src="https://user-images.githubusercontent.com/381895/132324412-3ebce4a5-680d-46d4-9100-c859171ce8d3.png">

**Comment by fmrsabino** [comment]
Conclusions of the meeting about this issue with  @dasanra @fmrsabino @katspaugh  @rmeissner

**Decision**
We decided that we will go with the original proposal of having a flag returned by the `safe-config-service`:

```javascript
GET api/v1/chains
{
  "l2": <boolean>
}
```

**Why not have the contract addresses returned as suggested in one iteration?**
The proposal for having the contracts returned by the `config-service` raised some security concerns where we have a centralised point where this data is returned – the safe creation payload would be just used as is with any connected wallet on the `safe-react` side.

An additional check on the CGW was proposed but would still rely on trusting our infrastructure.

Given the security concerns raised above, the preferred option is still to rely on the current configuration of the `safe-deployments` repo because it involves more parties/coordination and the information is publicly available – `safe-deployment` releases, `safe-config-service` data (l2 flag) and open cross checking (since the repositories are public. This is more in line with our vision with trust-less deployments.

**What about the allowances module address?**

The allowances module is currently not available in the `safe-deployments` and it was suggested to be added as part of this ticket in a previous iteration.

A followup meeting/ticket will tackle if this address is going to be added to the `safe-deployments` repo and in which way.

**Comment by katspaugh** [comment]
@fmrsabino can you post a staging link to the API request with the added flag?

**Comment by fmrsabino** [comment]
> @fmrsabino can you post a staging link to the API request with the added flag?

The endpoint is the same as before. It's under `/api/v1/chains/`

**Comment by katspaugh** [comment]
Could you paste the entire URL?

**Comment by fmrsabino** [comment]
> Could you paste the entire URL?
> Edit: I suggest we always post a link to staging for GET requests, so that we can QA the ticket quickly.

Here: https://safe-config.staging.gnosisdev.com/api/v1/chains/

**Comment by katspaugh** [comment]
Works as expected, thank you ✅
