### ISSUE TITLE
Update WalletConnect bridge to https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/1.6.6

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-config-service#320]

**Comment by fmrsabino** [comment]
The relay service/bridge is on version `1.0.1` so we'll use that one: https://github.com/WalletConnect/walletconnect-monorepo/blob/468148cb70998a9512ffa35770d95a8f80e407bd/servers/relay/package.json#L4

**Comment by fmrsabino** [comment]
We have decided to not move forward with the update given that the benefit of updating the bridge is not clear yet and might be related with bigger changes:

The `bridge` that we are using on our infrastructure is from this repo https://github.com/WalletConnect/node-walletconnect-bridge (latest release `v1.0.0-beta`).

A new `relay-server` was added under the `v2` branch of the new monorepo of WalletConnect – https://github.com/WalletConnect/walletconnect-monorepo/tree/v2.0/servers/relay

The version of this `relay` is `1.0.1` https://github.com/WalletConnect/walletconnect-monorepo/blob/468148cb70998a9512ffa35770d95a8f80e407bd/servers/relay/package.json#L4

Since `1.0.1` is part of a `v2` branch/bundle this might imply that there are bigger changes that we need to evaluate. Additionally we need to confirm what is the relationship between the `bridge 1.0.0-beta` and `relay 1.0.1` (different names for the service).

Given this I will close down the issue.

**Comment by Uxio0** [comment]
> Since 1.0.1 is part of a v2 branch/bundle this might imply that there are bigger changes that we need to evaluate. Additionally we need to confirm what is the relationship between the bridge 1.0.0-beta and relay 1.0.1 (different names for the service).

Did you ask WC team about this?

**Comment by fmrsabino** [comment]
> > Since 1.0.1 is part of a v2 branch/bundle this might imply that there are bigger changes that we need to evaluate. Additionally we need to confirm what is the relationship between the bridge 1.0.0-beta and relay 1.0.1 (different names for the service).
> 
> Did you ask WC team about this?

I didn't. The original task was to update the bridge `v1.6.6` (which does not exist). I would say that we need to re-evaluate the need for the update.

**Comment by Uxio0** [comment]
> I didn't. The original task was to update the bridge `v1.6.6` (which does not exist). I would say that we need to re-evaluate the need for the update.

Agree, just curious 😉
